### ISSUE TITLE
plugin does not appear to work in foreman 1.12.1

### ISSUE THREAD

**Issue by sirinek** [theforeman/foreman_deployments#25]
Please forgive me if this is user error, but I have been trying to get the foreman_deployments plugin to work on foreman 1.12.1 without success. Foreman refuses to start.

This is a RHEL7 host. Output is attached

[foreman_errors.txt](https://github.com/theforeman/foreman_deployments/files/425179/foreman_errors.txt)

Thanks

Bill

**Comment by ShimShtein** [comment]
I have submitted a PR (https://github.com/theforeman/foreman_deployments/pull/26) that makes it work again. If you want to early-test the PR, you are more than welcome. Anyway you can contact me on the IRC if you have any questions.

**Comment by ShimShtein** [comment]
#26 merged.
You can try it now.

Thanks and sorry for the long response times!
